### ISSUE TITLE
update setPlayerMove method

### ISSUE THREAD

**Issue by cbankr22** [chandler-thornton/Tic-Tac-Toe#1]
turn it into this
	public static void setPlayerMove(int pos, int player) {

	    if(player == 1) {
	    	board[(pos - 1) / 3][(pos - 1) % 3] = 'X';
	    } else {
	    	board[(pos - 1) / 3][(pos - 1) % 3] = 'O';
	    }
	}

**Comment by chandler-thornton** [comment]
Doesn't work; giving ArrayOutOfBoundsException
